# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hbui-vu <huong.buivu@gmail.com>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/23 08:41:32 by hbui-vu           #+#    #+#              #
#    Updated: 2022/08/23 09:21:22 by hbui-vu          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = 
SRCS =  ft_putchar.c ft_putstr.c ft_strcmp.c ft_strlen.c ft_swap.c 


all: ${NAME}

${NAME}:
	gcc -o ${NAME} ${SRCS}

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f ${NAME}

re: fclean all

libft.a:




